AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  NameOfService:
    Type: String
    Description: Name of service
    Default: Default-Name-of-service
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - m1.small
      - m1.large
    Description: Enter t2.micro, t2.small, m1.small, or m1.large, Default is t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of EC2 Key Pair

Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: ami-0df435f331839b2d6
    us-east-2:
      AMI: ami-0a0d9cf81c479446a
    us-west-1:
      AMI: ami-0c87a756f3fd22df2

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              php: []
              httpd: []
              wget: []
              unzip: []
              git: []
          commands:
            test:
              command: "wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip && unzip 2135_mini_finance.zip && cp -r 2135_mini_finance/* /var/www/html"
          files:
            /var/www/html/hello.html:
              content: !Sub |
                <html>
                  <head>
                    <title>Hello epta</title>
                  </head>
                  <body>
                    <h1>Httmll йопта</h1>
                  </body>
                </html>
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref VprofileSG
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Ensure if AWS CFN bootstrap is latest
          yum install -y aws-cfn-bootstrap
          # Install the files and packages from metadata
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServer --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServer --region ${AWS::Region}

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  PrintSomeInfo:
    Value: !GetAtt WebServer.PublicDnsName
