AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    NameOfService:
      Type: String
      Description: Name of service
    InstanceTypeParameter:
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - t2.small
        - m1.small
        - m1.large
      Description: Enter t2.micro, t2.small, m1.small, or m1.large, Default is t2.micro
    KeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: Name of EC2 Key Pair

Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: ami-0df435f331839b2d6
    us-east-2:
      AMI: ami-09d9029d9fc5e5238
    us-west-1:
      AMI: ami-0c87a756f3fd22df2

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
