---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    - name: Install pip
      ansible.builtin.dnf:
        name: python-pip
        state: present

    - name: Install pymysql
      ansible.builtin.pip:
        name: pymysql
        state: present

    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database
      community.mysql.mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: accounts
        state: present

    - name: Create database user with all database privileges
      community.mysql.mysql_user:
        name: admin
        password: 'admin123'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

