all:
  hosts:
    web01:
      ansible_host: 172.31.43.155
    web02:
      ansible_host: 172.31.44.90
    db01:
      ansible_host: 172.31.47.71

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_virginia:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: clientkey.pem

