---
# tasks file for post-install
- name: Install ntp agent on Amazon 2023
  yum:
    name: "{{item}}"
    state: present
  when: ansible_distribution == 'Amazon'
  loop:
    - chrony
    - wget
    - git
    - zip
    - unzip

- name: Install ntp agent on Ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Start service ntp agent on Amazon 2023
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == 'Amazon'

- name: Start service ntp agent on Ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu'

- name: Create a folder
  file:
    path: "{{dir1}}"
    state: directory
- name: Banner file
  copy:
    content: "# This server is managed by ansible. No manual changes maza faka!"
    dest: /etc/motd

- name: Deploy ntp agent conf on Amazon2023
  template:
    src: ntpconf_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "Amazon"
  notify:
    - reStart service ntp agent on Amazon2023

- name: Deploy ntp agent conf on Ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - reStart service ntp agent on Ubuntu

- name: Dump file
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt

