---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on Amazon 2023
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == 'Amazon'
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install ntp agent on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start service ntp agent on Amazon 2023
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == 'Amazon'

    - name: Start service ntp agent on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'
