---
- name: Print facts
  hosts: all
  tasks:
    - name: print OS name
      debug:
        var: ansible_os_family
    - name: print RAM memory
      debug:
        var: ansible_memory_mb.real.free
    - name: print processor
      debug:
        var: ansible_processor[2]