---
- name: DBserver setup
  hosts: dbservers
  become: yes
  vars:
    dbname: electric
    dbuser: admin
    dbpass: tesla
  tasks:
    - name: Install mariadb-server
      ansible.builtin.dnf:
        name: mariadb105-server
        state: present

    - name: Install pip
      ansible.builtin.dnf:
        name: python-pip
        state: present

    - name: Install pymysql
      ansible.builtin.pip:
        name: pymysql
        state: present

    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - debug:
        msg: "The dbname is {{dbname}}"
    - name: Create a new database
      community.mysql.mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{dbname}}"
        state: present

    - debug:
        var: dbuser
    - name: Create database user with all database privileges
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbout

    - name: print dbout variable
      debug:
        var: dbout

